=== SpacemanRiff/spring-semester-project/demos/HybridPizzaOrderXML/PizzaArguments.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="http://www.w3schools.com"
		   attributeFormDefault="unqualified" 
		   elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://www.w3schools.com PizzaArguments.xsd">
		   
  <xs:element name="arguments">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="description"/>
              <xs:element type="xs:string" name="type"/>
              <xs:element type="xs:integer" name="restrictedcount" minOccurs="0"/>
              <xs:element type="xs:string" name="restricted" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element type="xs:string" name="default" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="type" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SpacemanRiff/spring-semester-project/demos/XMLPizzaDemo/PizzaArguments.xml
<?xml version="1.0"?>
<arguments xmlns="http://www.w3schools.com"
		   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:schemaLocation="http://www.w3schools.com PizzaArguments.xsd">
	<argument type = "positional">
		<name>size</name>
		<description>The size of the pizza (Small, Medium, or Large)</description>
		<type>STRING</type>
		<restrictedcount>6</restrictedcount>
		<restricted>small</restricted>
		<restricted>Small</restricted>
		<restricted>medium</restricted>
		<restricted>Medium</restricted>
		<restricted>large</restricted>
		<restricted>Large</restricted>
	</argument>

	<argument type = "positional">
		<name>crust</name>
		<description>The style of pizza crust</description>
		<type>STRING</type>
	</argument>

	<argument type = "positional">
		<name>toppings</name>
		<description>The number of toppings for the pizza</description>
		<type>INTEGER</type>
	</argument>

	<argument type = "required">
		<name>quantity</name>
		<description>Allows you to order multiple of the same pizza</description>
		<type>INTEGER</type>
		<default>1</default>
	</argument>

	<argument type = "named">
		<name>drink</name>
		<description>The drink you will have with your pizza</description>
		<type>STRING</type>
		<default>No Drink</default>
	</argument>

</arguments>
